### ISSUE TITLE
Scrolling long texts

### ISSUE THREAD

**Issue by Emmpunkt** [gavinlyonsrepo/SSD1306_OLED_RPI#4]
Hello,
is it possible to scroll a long text? Wider as the display width?
I`m using one of this tiny displays (0,91") and want to show Interpret and song title as marquee in full hight.
Nice and clean library by the way.....

**Comment by gavinlyonsrepo** [comment]
Hi 

The horizontal screen scroll is tested in: OLED_FUNCTIONS example - Test 504 Scroll Screen ,
But in your case you will have to put the text in a String object or character array and scroll it manually in code. 

regards

**Comment by gavinlyonsrepo** [comment]
Hi 

I have created a simple example gist here 
https://gist.github.com/gavinlyonsrepo/a15fffe0cc6fbda893742d75991cd4ea

to scroll text using C++ string object

regards

**Comment by Emmpunkt** [comment]
Wow, this is very nice of you!
I tested it and it works. Not as smooth as i would like it, but maybe i can find a way around it...
Thank you very much, i´m a step further...
